spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userauthdb?createDatabaseIfNotExist=true&user=root&password=root&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:      hibernate:
        dialect:  org.hibernate.dialect.MySQL8Dialect
server:
  port: 2212
  
