spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userauthdb?autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 2212